name: Synopsys-Actions
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

   
  workflow_dispatch:
jobs:
  build:
    runs-on: [ mac ]

    steps:
    - uses: actions/checkout@v3
    
    - name: Synopsys Detect
      id: blackduck
      uses: synopsys-sig/synopsys-action@v1.2.0
      with:
         blackduck_url: ${{ secrets.BLACKDUCK_URL }}
         blackduck_apitoken: ${{ secrets.BLACKDUCK_API_TOKEN }}
         blackduck_automation_fixpr: true
         blackduck_scan_full: true
        #  blackduck_automation_prcomment: true
         github_token: ${{ secrets.PAT }}
         include_diagnostics: true

      
      env: 
         DETECT_PROJECT_NAME: "Blackduck-Synopsys-Action-Example-NodeJS-Webgoat"
         DETECT_PROJECT_VERSION_NAME: "1.0"
         DETECT_TOOLS_EXCLUDED: 'SIGNATURE_SCAN'
         BLACKDUCK_TRUST_CERT: true
         DETECT_PROJECT_APPLICATION_ID: '248982' 
         DETECT_PROJECT_TAGS: "bottomzone,contractors,internal,nexus,nonmodifiedoss,notdistributed,weboat"
         DETECT_WAIT_FOR_RESULTS: true