name: Security Checks
on: [push]

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
          ref: master
       - name: Building Docker Node-Goat Image
         run: docker-compose build
       - name: Launching the app
         run: docker-compose up --detach

- name: OWASP ZAP Baseline Scan
  # You may pin to the exact commit or the version.
  # uses: zaproxy/action-baseline@7cea08522cd386f6c675776d5e4296aecf61f33b
  uses: zaproxy/action-baseline@v0.7.0
  with:
    # GitHub Token to create issues in the repository
    token: $
    # Target URL
    target: "http://localhost:4000"
    # Relative path of the ZAP configuration file
    rules_file_name: # optional
    # The Docker file to be executed
    docker_name: # default is owasp/zap2docker-stable
    # Additional command line options
    cmd_options: # optional
    # The title for the GitHub issue to be created
    issue_title: Security Tests
    # The action status will be set to fail if ZAP identifies any alerts during the baseline scan
    fail_action: false
    # The action will file the report to the GitHub issue using the issue_title input
    allow_issue_writing: # optional, default is true
